### PR TITLE
refactor: add `query` alias to `params` option

### LINKED ISSUE #73: rename `params` to `query`
`params` can have different meanings in different contexts. `fetch(URL, { query }` is probably more readable.

### PR DESCRIPTION
**Pull request by huynl-96**
Resolves #73

### CODE REVIEW

**Comment by pi0** [comment]
Thanks for PR @huynl-96. I think we can introduce query and deprecate params without breaking changes and it is good to go.

**Comment by huynl-96** [comment]
@pi0 I've added a deprecated warning for `params`. Thanks for your advice

**Comment by pi0** [comment]
Hi @huynl-96. Sorry it took long for me back to this. I had been thinking it might be better to support both options as alias (without deprecation) because the same "query string" is also named "URL search params" in other standards. Also using "Query search params" in docs to make it readable in both ways.

**Comment by huynl-96** [comment]
@pi0 
> Sorry it took long for me back to this 

Don't worry about it, hope you are feeling better now.
It's good to finally have you back with us

> I had been thinking it might be better to support both options as alias (without deprecation) because the same "query string" is also named "URL search params" in other standards. Also using "Query search params" in docs to make it readable in both ways.

Looks good to me, no concern about it

**Pull request merged**
